name: Generate Snake

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight
  workflow_dispatch:  # Allows manual trigger

jobs:
  generate-snake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create dist directory
        run: mkdir -p dist  # Ensure the dist directory is created before saving the SVG

      - name: Generate Snake Animation
        uses: Platane/snk@v3.2.4
        with:
          github_user_name: ${{ github.repository_owner }}
          # Optional, you can also specify the date range
          date_range: last_year
          # Output file path
          outputs: dist/snake.svg

      - name: Commit and Push Snake Animation
        run: |
          git config --global user.email "your-email@example.com"
          git config --global user.name "Your Name"
          git add dist/snake.svg
          git diff --cached --quiet || (git commit -m "Update Snake Animation" && git push)
